# Generated by Django 4.2.6 on 2023-10-15 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Integration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='googlerequestmodel',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
